version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mutant_api/
    command: uvicorn api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on: 
     - db

  db:
    image: postgres
    container_name: mutant-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql

volumes:
  data:
